import json,re,time
from pathlib import Path
from genlayer_py import create_client,create_account
from genlayer_py.chains import studionet
ROOT=Path(__file__).parents[1];ENV=(ROOT.parents[3]/'accounts.env').read_text(encoding='utf-8');DEP=json.loads((ROOT/'deployment.json').read_text())
def v(n):return re.search(rf'^{n}="?([^"\r\n]+)',ENV,re.M).group(1).strip()
def wait(c,h):
 r=c.wait_for_transaction_receipt(transaction_hash=h,status='FINALIZED',retries=180,interval=5000,full_transaction=True);leader=((r.get('consensus_data',{}).get('leader_receipt') or [{}])[0]).get('execution_result');assert 'MAJORITY_AGREE' in str(r.get('result_name','')).upper() and str(leader).upper()=='SUCCESS';return r
owner=create_account(account_private_key=v('ACCOUNT_2_GENLAYER_PRIVATE_KEY'));runner=create_account(account_private_key=v('ACCOUNT_3_GENLAYER_PRIVATE_KEY'));challenger=create_account(account_private_key=v('ACCOUNT_4_GENLAYER_PRIVATE_KEY'));finalizer=create_account(account_private_key=v('ACCOUNT_5_GENLAYER_PRIVATE_KEY'));co=create_client(chain=studionet,account=owner);cr=create_client(chain=studionet,account=runner);cf=create_client(chain=studionet,account=finalizer);address=DEP['contractAddress'];commit=DEP['sourceCommit'];item='REMEDIATION-'+str(int(time.time()));spec=f'https://raw.githubusercontent.com/warnedwarn/fixture-forge/{commit}/evidence/frozen-spec.txt';output=f'https://cdn.jsdelivr.net/gh/warnedwarn/fixture-forge@{commit}/evidence/observed-output.txt';artifact=f'https://raw.githack.com/warnedwarn/fixture-forge/{commit}/evidence/run-artifact.txt';print('record='+item,flush=True);a=co.write_contract(address=address,function_name='specify',args=[item,'Canonical UTF-8 parser fixture',runner.address,challenger.address,'Python 3.13 / UTF-8 / Linux','sha256:8ed3f6ad685b959ead7022518e1af76cd816f8e8ec7ccdda1ed4018e8f2223f8',spec,300]);print('specify_tx='+a,flush=True);wait(co,a);b=cr.write_contract(address=address,function_name='record_run',args=[item,output,artifact]);print('record_run_tx='+b,flush=True);wait(cr,b);state=co.read_contract(address=address,function_name='get_fixture',args=[item]);assert state['state']=='RUN_RECORDED' and len(state['spec_digest'])==64;print('challenge window open; waiting for permissionless finalization',flush=True);time.sleep(305);c=cf.write_contract(address=address,function_name='finalize',args=[item]);print('finalize_tx='+c,flush=True);wait(cf,c);state=co.read_contract(address=address,function_name='get_fixture',args=[item]);assert state['state']=='VERIFIED';print(json.dumps({'id':item,'state':state['state'],'specDigest':state['spec_digest'],'transactions':{'specify':a,'recordRun':b,'finalize':c},'author':owner.address,'runner':runner.address,'challenger':challenger.address,'finalizer':finalizer.address,'roleEvidence':'separate user-controlled demo addresses, not independent authorities'}),flush=True)
